import { Category, User, Training, Attendance, Financial, Position } from '@/types'

export const mockCategories: Category[] = [
  {
    id: '1',
    name: 'Misto',
    days_of_week: ['Segunda', 'Quarta'],
    start_time: '19:00',
    end_time: '21:00',
    location: 'Ginásio Central',
    observations: 'Treino aberto para todos os níveis',
    price_drop_in: 30,
    price_weekly: 80,
    price_monthly: 200,
    price_semiannual: 1000,
    price_annual: 1800,
  },
  {
    id: '2',
    name: 'Feminino',
    days_of_week: ['Terça', 'Quinta'],
    start_time: '18:00',
    end_time: '20:00',
    location: 'Ginásio Central',
    price_drop_in: 30,
    price_weekly: 80,
    price_monthly: 200,
    price_semiannual: 1000,
    price_annual: 1800,
  },
  {
    id: '3',
    name: '+30',
    days_of_week: ['Sábado'],
    start_time: '09:00',
    end_time: '11:00',
    location: 'Quadra Coberta Norte',
    observations: 'Para atletas acima de 30 anos',
    price_drop_in: 35,
    price_weekly: 90,
    price_monthly: 220,
    price_semiannual: 1100,
    price_annual: 2000,
  },
]

export const mockPositions: Position[] = [
  { id: '1', name: 'Central' },
  { id: '2', name: 'Líbero' },
  { id: '3', name: 'Ponteiro' },
  { id: '4', name: 'Oposto' },
  { id: '5', name: 'Levantador' },
  { id: '6', name: 'Técnico' },
]

export const mockUsers: User[] = [
  {
    id: '1',
    role: 'coordinator',
    name: 'Gabriel Rayo',
    dob: '1990-05-15',
    cpf: '123.456.789-00',
    rg: '12.345.678-9',
    origin_street: 'Rua das Flores',
    origin_neighborhood: 'Centro',
    origin_zip: '01310-100',
    destination_street: 'Av. Paulista',
    destination_neighborhood: 'Bela Vista',
    destination_zip: '01311-200',
  },
  {
    id: '2',
    role: 'member',
    name: 'Ana Silva',
    dob: '1995-08-22',
    cpf: '987.654.321-00',
    rg: '98.765.432-1',
    origin_street: 'Rua Augusta',
    origin_neighborhood: 'Consolação',
    origin_zip: '01305-000',
    destination_street: 'Av. Paulista',
    destination_neighborhood: 'Bela Vista',
    destination_zip: '01311-200',
  },
  {
    id: '3',
    role: 'member',
    name: 'Carlos Mendes',
    dob: '1988-11-10',
    cpf: '456.789.123-00',
    rg: '45.678.912-3',
    origin_street: 'Rua da Consolação',
    origin_neighborhood: 'Consolação',
    origin_zip: '01301-000',
    destination_street: 'Av. Paulista',
    destination_neighborhood: 'Bela Vista',
    destination_zip: '01311-200',
  },
  {
    id: '4',
    role: 'member',
    name: 'Fernanda Costa',
    dob: '1993-03-18',
    cpf: '321.654.987-00',
    rg: '32.165.498-7',
    origin_street: 'Alameda Santos',
    origin_neighborhood: 'Jardins',
    origin_zip: '01419-001',
    destination_street: 'Av. Paulista',
    destination_neighborhood: 'Bela Vista',
    destination_zip: '01311-200',
  },
  {
    id: '5',
    role: 'member',
    name: 'Lucas Oliveira',
    dob: '1997-07-05',
    cpf: '654.321.987-00',
    rg: '65.432.198-7',
    origin_street: 'Rua Haddock Lobo',
    origin_neighborhood: 'Cerqueira César',
    origin_zip: '01414-001',
    destination_street: 'Av. Paulista',
    destination_neighborhood: 'Bela Vista',
    destination_zip: '01311-200',
  },
]

export const mockTrainings: Training[] = [
  { id: '1', category_id: '1', date: '2026-04-07', status: 'done' },
  { id: '2', category_id: '1', date: '2026-04-09', status: 'done' },
  { id: '3', category_id: '1', date: '2026-04-14', status: 'scheduled' },
  { id: '4', category_id: '1', date: '2026-04-16', status: 'scheduled' },
  { id: '5', category_id: '2', date: '2026-04-08', status: 'done' },
  { id: '6', category_id: '2', date: '2026-04-10', status: 'done' },
  { id: '7', category_id: '2', date: '2026-04-15', status: 'scheduled' },
]

export const mockAttendances: Attendance[] = [
  { id: '1', training_id: '1', user_id: '2', status: 'present' },
  { id: '2', training_id: '1', user_id: '3', status: 'present' },
  { id: '3', training_id: '1', user_id: '4', status: 'absent' },
  { id: '4', training_id: '2', user_id: '2', status: 'present' },
  { id: '5', training_id: '2', user_id: '3', status: 'absent' },
  { id: '6', training_id: '2', user_id: '4', status: 'present' },
]

export const mockFinancials: Financial[] = [
  { id: '1', user_id: '2', category_id: '1', month: 4, year: 2026, status: 'paid' },
  { id: '2', user_id: '3', category_id: '1', month: 4, year: 2026, status: 'pending' },
  { id: '3', user_id: '4', category_id: '1', month: 4, year: 2026, status: 'paid' },
  { id: '4', user_id: '5', category_id: '1', month: 4, year: 2026, status: 'pending' },
  { id: '5', user_id: '2', category_id: '2', month: 4, year: 2026, status: 'paid' },
]
